#%RAML 1.0
title: Documentation of REST services for INF5190 project.
mediaType: application/json
types:
  Piscines:
    properties:
        id:
            type: number
            required: true
        id_uev:
            type: string
            required: true
        type:
            type: string
            required: true
        nom:
            type: string
            required: true
        arrondissement:
            type: string
            required: true
        adresse:
            type: string
            required: true
        propriete:
            type: string
            required: true
        gestion:
            type: string
            required: true
        point_x:
            type: string
            required: true
        point_y:
            type: string
            required: true
        equipement:
            type: string
            required: true
        long:
            type: string
            required: true
        lat:
            type: string
            required: true

  Glissades:
    properties:
        id:
            type: number
            required: true
        nom:
            type: string
            required: true
        nom_arrondissement:
            type: string
            required: true
        cle_arrondissement:
            type: string
            required: true
        date_maj_arrondissement:
            type: string
            required: true
        ouvert:
            type: number
            required: true
        deblaye:
            type: number
            required: true
        condition:
            type: string
            required: true
  
  Patinoires:
    properties:
        id:
            type: number
            required: true
        nom:
            type: string
            required: true
        nom_arrondissement:
            type: string
            required: true
        date_maj:
            type: string
            required: true
        ouvert:
            type: number
            required: true
        deblaye:
            type: number
            required: true
        arrose:
            type: number
            required: true
        resurface:
            type: number
            required: true
  Installation:
    properties:
        id:
            type: number
            required: true
        nom:
            type: string
            required: true
        nom_arrondissement:
            type: string
            required: true
/api:
  /installations:
    get:
      description: Liste des installations renseignées dans la base de données.
      queryParameters:
        arrondissement:
          description: Une chaîne de caractères qui donne le nom d'un arrondissement
          type: string
          required: true
          example: LaSalle
      responses:
        200:
          description: La liste des installations a été correctement envoyée.
          body:
            application/json:
              types: Piscines, Glissades et Patinoires
    /2021:
      get:
        description: Liste des installations mises à jour en 2021.
        responses:
          200:
            body:
              application/json:
                type: Glissades et Patinoires
      /xml:
        get:
          description: Liste des installations mises à jour en 2021 au format xml.
          responses:
            200:
              body:
                application/xml:
                  type: Glissades et Patinoires
      /csv:
        get:
          description: Fichier csv des installations mises à jour en 2021.
          responses:
            200:
              body:
                file/csv:
                  type: Installation
  /installation:
    get:
      description: Objet dictionnaire qui représente une installation.
      queryParameters:
        nom:
          description: Une chaîne de caractères qui donne le nom de l'installation
          type: string
          required: true
          example: Bain Quintal
      responses:
        200:
          description: L'installation recherchée a été correctement envoyée.
          body:
            application/json:
              type: Installation