#%RAML 1.0
title: Documentation of REST services for INF5190 project.
mediaType: application/json
types:
  Piscines:
    properties:
        id:
            type: int
            required: true
        id_uev:
            type: varchar
            required: true
        type:
            type: varchar
            required: true
        nom:
            type: varchar
            required: true
        arrondissement:
            type: varchar
            required: true
        adresse:
            type: varchar
            required: true
        propriete:
            type: varchar
            required: true
        gestion:
            type: varchar
            required: true
        point_x:
            type: varchar
            required: true
        point_y:
            type: varchar
            required: true
        equipement:
            type: varchar
            required: true
        long:
            type: varchar
            required: true
        lat:
            type: varchar
            required: true

  Glissades:
    properties:
        id:
            type: int
            required: true
        nom:
            type: varchar
            required: true
        nom_arrondissement:
            type: varchar
            required: true
        cle_arrondissement:
            type: varchar
            required: true
        date_maj_arrondissement:
            type: varchar
            required: true
        ouvert:
            type: number
            required: true
        deblaye:
            type: number
            required: true
        condition:
            type: varchar
            required: true
  
  Patinoires:
    properties:
        id:
            type: int
            required: true
        nom:
            type: varchar
            required: true
        nom_arrondissement:
            type: varchar
            required: true
        date_maj:
            type: varchar
            required: true
        ouvert:
            type: number
            required: true
        deblaye:
            type: number
            required: true
        arrose:
            type: number
            required: true
        resurface:
            type: number
            required: true
/api:
  /installations:
    get:
      description: Liste des installations renseignées dans la base de données.
      queryParameters:
        arrondissement:
          description: Une chaîne de caractères qui donne le nom d'un arrondissement
          type: string
          required: true
          example: LaSalle
      responses:
        200:
          description: La liste des installations a été correctement envoyée.
          body:
            application/json:
              type: List[dict]
    /2021:
      get:
        description: Liste des installations mises à jour en 2021.
        responses:
          200:
            body:
              application/json:
                type: List[dict]
      /xml:
        get:
          description: Liste des installations mises à jour en 2021 au format xml.
          responses:
            200:
              body:
                application/xml:
                  type: List[dict]


/api:
  /person:
    get:
      description: Extract the data of all the persons.
      responses:
        200:
          body:
            application/json:
              type: ExistingPerson[]
    post:
      description: Create a new person.
      body:
        application/json:
          type: NewPerson
          example:
            lastname: Jackson
            firstname: Michael
            age: 54
      responses:
        201:
          description: The person was successfully created.
          body:
            application/json:
              type: ExistingPerson
              example:
                id: 5
                lastname: Jackson
                firstname: Michael
                age: 54
    /{id}:
      get:
        description: Extract the data of one person, specified by it's id.
        responses:
          200:
            body:
              application/json:
                type: ExistingPerson
          404:
            description: The specified identifier does not exist.
      put:
        description: Modify the data of one person, specified by it's id. It is not possible to change the id.
        body:
          application/json:
            type: ExistingPerson
        responses:
          200:
            body:
              application/json:
                type: ExistingPerson
          404:
            description: The specified identifier does not exist.
      delete:
        description: Delete completely the data of a person, specified by it's id.
        responses:
          200:
            description: The person was deleted successfully.
          404:
            description: The specified identifier does not exist.